### ISSUE TITLE
SNMP Scanner and Remaining SNMP Plugins

### ISSUE THREAD

**Issue by jamfwright** [owtf/owtf#348]
Hello,

First off, great job on all of this!

I'm on my first run with all plugins enabled to see what happens.  I notice a potential enhancement already, which would improve the efficiency of OWTF.

When the SNMP scanner is run, specifically "/opt/metasploit/apps/pro/msf3/msfcli auxiliary/scanner/snmp/snmp_enumusers", if the connection is refused it would then seem unnecessary to then also run the Metasploit login bruteforce "/opt/metasploit/apps/pro/msf3/msfcli auxiliary/scanner/snmp/snmp_login".

There is a substantial time sink in trying to then bruteforce a service that is not actually running.

What may be a better way would be to nmap the target (or other port discovery) and then apply only the related plugins, even if all are selected - with an option to run the dynamically disabled ones anyways.

This would provide faster reconnaissance overall, but still allow the tester to be thorough if they wish.  I do note plugins can be manually skipped in the Worker page, being a little more intelligent about which enabled plugins to run would be rather nice.

Many thanks,
James

**Comment by anantshri** [comment]
did we made any progress on this issue.

**Comment by delta24** [comment]
@anantshri This would require changing the way plugins run and queue. (requiring a rewrite). 
@7a @DePierre move this to reboot? I am thinking to go into a feature freeze - support (bugs, maintenance only) while we work on reboot.

**Comment by DePierre** [comment]
@delta24 However you feel. It would indeed require some rework in the way plugins are run but I think that it can be done if someone is motivated enough. It should also be included in the reboot, absolutely.

**Comment by delta24** [comment]
@DePierre this is relevant not only for this issue but many more - like this general issue https://github.com/owtf/reboot/issues/25

**Comment by DePierre** [comment]
@delta24 The root-cause of these issues is simply the lack of inter-dependency in our plugin mechanism. Sure it's relevant to many issues like this one, but all would be closed if we had that dependency mechanism.

Like I said, it should be part of the reboot project but it could also be implemented in the current code base. It's basically

+ An extra attribute to the plugin (we already have an 'extra' parameter implemented, so we could use it) to specify the dependency
+ A status state to know if a plugin was successful or not (do we have that already? this might be trickier since it's dependent on the output of the plugin)
+ The plugin handler to modify (to have the logic *if one of the plugin in the dependency list has failed, skip current plugin*).

I honestly believe that it wouldn't be that much of a patch (although much larger than a patch for a typo of course) and would be doable for the current code base (instead of waiting for the reboot).

**Comment by viyatb** [comment]
Moved to https://github.com/owtf/community-plugins/issues/4.
