### ISSUE TITLE
[develop] Unable to resolve 'aux' when selecting an AUX plugin

### ISSUE THREAD

**Issue by DePierre** [owtf/owtf#386]
IIRC OWTF's current version does not support the AUX plugins (@tunnelshade could you confirm?) but a weird bug appears when selecting an ``AUX`` plugin anyway.

I was trying to reproduce #128 by reusing the command given by @marioskourtesis but I got the following output:

```bash
$ ./owtf.py -o Spear_Phishing http://127.0.0.1 

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
[-] Defaulting Plugin Group to 'aux' based on list of plugins supplied
[*] OWTF Version: 1.0.1, Release: LionHeart (Beta) 
[-] Loading framework please wait..
[!] Unable to resolve: 'aux'
[!] Unable to resolve: 'aux'
[*] 127.0.0.1:8008 <-- HTTP(S) Proxy to which requests can be directed
[*] http://127.0.0.1:8009 <-- Web UI URL
```

**Comment by Sentient07** [comment]
#395

**Comment by DoomTaper** [comment]
@DePierre the issue lies in the [L#185](https://github.com/owtf/owtf/blob/develop/owtf.py#L185), and on a later stage it is not checked whether scope is auxiliary or not , because in that case I think the flow will be different. So @delta24 @DePierre @tunnelshade @7a can you brief me about how aux plugins are made to run from CLI, then I will make the changes accordingly.

**Comment by DarKnight--** [comment]
@DoomTaper this issue has been fixed in my commit. Now OWTF is able to resolve the 'aux' -> 'auxiliary' plugins.

**Comment by DoomTaper** [comment]
@DarKnight-- I have pulled your commit and yes OWTF is able to resolve aux plugin through -l option but are you able to run the given command `./owtf.py -o Spear_Phishing http://127.0.0.1` .? The error `[!] Unable to resolve: 'aux'` is due to adding aux to target scope which at later stage is not checked as I said in my previous comment. You have just enable the `-l auxuliary` functionality and IMO it doesn't fix this issue.
Correct me If I am wrong @DarKnight-- .

**Comment by DarKnight--** [comment]
Yeah my bad, I didn't get the error. It was probably because my machine was able to resolve it (as shown [here](http://imgur.com/N7B0q5p)). Yes the problem lies in `owtf.py line 180-185`. As this scope is later used to get target.
