### ISSUE TITLE
replace msfcli with msfconsole -x or -r

### ISSUE THREAD

**Issue by anantshri** [owtf/owtf#399]
We need to replace msfcli with its newer counterparts.

https://github.com/rapid7/metasploit-framework/issues/3802
<pre>
[!] ************************************************************************
[!] *               The utility msfcli is deprecated!                      *
[!] *            It will be removed on or about 2015-06-18                 *
[!] *              Please use msfconsole -r or -x instead                  *
[!] *  Details: https://github.com/rapid7/metasploit-framework/pull/3802   *
[!] ************************************************************************
</pre>

**Comment by 7a** [comment]
+1

**Comment by qgrosperrin** [comment]
I'm running into some issues using the `msfconsole -x` alternative to `msfcli` and was hoping to get some directions here on how to use it properly. To me, it appears:
- 1. slower than msfcli  
- 2. too verbose  
- 3. the command line doesn't look very clean

Below are some details about these comments.

1. 
I have noted that the `msfconsole` alternative to `msfcli` is at least two times slower on my machine. I'm guessing this is because `msfconsole` tries to load everything, not taking into account it runs as a command line utility (as opposed to interactive mode). Is there a way to use `msfconsole -x/-r` and not have it load everything ?

Sample exec times from my machine
```
time msfcli auxiliary/scanner/finger/finger_users USERS_FILE=/usr/share/wordlis
ts/metasploit/unix_users.txt RHOSTS=192.168.231.145 E
[...]
real    0m4.412s
user    0m3.288s
sys     0m1.080s
```

```
time msfconsole -x "use auxiliary/scanner/finger/finger_users; set USERS_FILE /
usr/share/wordlists/metasploit/unix_users.txt; set RHOSTS 192.168.231.145; exploit; exit"
[...]
real    0m11.185s
user    0m5.860s
sys     0m5.244s
```

2. `msfconsole` prints the metasploit framework welcome message and logo which is a lot more verbose than `msfcli` but this does not provide additional technical details.. Is there a way to have `msfconsole` not print all that information and instead just output the essential information that `msfcli` was exclusively returning ?

You might think this is not really important but I usually have `msfcli` run inside a wrapper function (BASH, Python or else) so having unnecessary verbose output can sometimes be a problem.

3. Is there any ways to have the command below executed in one go (not using ";" separated stacked commands), similar to msfcli ? 
`msfconsole -x "use auxiliary/scanner/finger/finger_users; set USERS_FILE /usr/share/wordlists/metasploit/unix_users.txt; set RHOSTS 192.168.231.145; exploit; exit"`

Something like the following would look cleaner imo, for instance:
`msfconsole -x "use auxiliary/scanner/finger/finger_users USERS_FILE=/usr/share/wordlists/metasploit/unix_users.txt RHOSTS=192.168.231.145"`

__Note__: I am not particularly attached to keeping `msfcli`. I just think the usability of `msfconsole -x/-r` is not as good at the moment. Hopefully this will be received as constructive criticism and help others if any documentation is provided here.
Thanks

**Comment by DePierre** [comment]
@qgrosperrin we welcome any criticims here :)

What I understand from your comment is that it should be posted to metasploit and not here.

I thank you for the benchmark though because it sounds really awful to have the new cli being twice slower than the older one. I guess they will enhance their system before droping the previous one.

Do you expect any specific answer about ``msfconsole`` here? Because that is not our project so... it would be difficul to answer.

**Comment by qgrosperrin** [comment]
@DePierre Damn, you're right... I'm on the wrong repo. I saw this issue being referenced on the official repo (https://github.com/rapid7/metasploit-framework/issues/3802) so without double-checking I assumed this one belonged to metasploit too.

Thanks for the heads up !

**Comment by calibersecurity** [comment]
Built OWTF on top of latest Kali repo's, looks like Rapid7 pulled MSFCLI out so now all the metasploit funcitons in OWTF have stopped running since MSFCLI is no longer found:

 The utility msfcli is deprecated!                      *
[!] *            It will be removed on or about 2015-06-18                 *
[!] *              Please use msfconsole -r or -x instead                  *
[!] *  Details: https://github.com/rapid7/metasploit-framework/pull/3802

**Comment by DePierre** [comment]
@calibersecurity We are working on that issue and it should be fixed quickly I hope.

**Comment by sealmindset** [comment]
I just comb through all the branches from adventure through ui looking to see if any changes were made to convert msfcli to msconsole dash x.  So far all of the branches are still using the now defunct metasploit cmd.  My workaround is to do a replacement:

grep -rl msfcli '/path/to/owtf' | xargs sed -i 's/msfcli /msfconsole -x /g'

Which affected these files:

/owtf/ui/owtf//profiles/general/default.cfg
/owtf/ui/owtf//profiles/general/default_backtrack.cfg
/owtf/ui/owtf//profiles/resources/default.cfg
/owtf/ui/owtf//profiles/resources/default_backtrack.cfg
/owtf/ui/owtf//scripts/import/metasploit/import_exploits.sh

It seems to be an easy fix.

**Comment by delta24** [comment]
@sealmindset a few points:
- All branches other than the `develop` are stale and should not to be used.
- The Metasploit fix is a little complicated than that - some of the command switches have also changed wrt the `msfconsole -x` change.
- If you can upfate and thoroughly test the relevant Metasploit commands, do open a PR! :)

**Comment by sealmindset** [comment]
@delta24 - Good point. It does appear to be working, but this is only based on the fact its not creating any errors. I still need to validate whether or not its returning the appropriate results using the new switch.
