### ISSUE TITLE
Occasionally workers do not notice if tool exited

### ISSUE THREAD

**Issue by viyatb** [owtf/owtf#439]
@7a : Skipfish clearly finished in the owtf_review directory:
`-rw-r--r--  1 root root 28056 Mar 11 16:10 index.html`

But the worker still waits for Skipfish to exit:

```
PID: 14662
Target: http://target.com
Plugin: Skipfish Unauthenticated
Type: active
Group: web
```

**Comment by DePierre** [comment]
@delta24 Have you been able to reproduce this bug in a fairly stable way? Would you have any recommendations to share with us in order to reproduce such behavior?

**Comment by delta24** [comment]
I only posted this from the @7a 's testing doc, please forward it to him xD.

**Comment by 7a** [comment]
Some bugs will only happen sometimes, especially when multiple processes
are involved :)

In this case, this was on a large assessment with 60+ targets. This means
there is a likely occasional race condition bug that might be around the
code that determines whether a subprocess has finished or not.

Imho, a possible way to approach this would be to review the affected code
and its surroundings, searching for a plausible root cause for this bug.
Replicating race conditions is too hard.

What I can say is that in this test, there were different stages, where a
bunch of targets where added to a scan in progress, this may or may not be
related :)

**Comment by DarKnight--** [comment]
@DePierre @delta24 @7a I have encountered this bug while running Nikto Unauthenticated OWTF-WVS-002, this is due to the some problem in PTP project of OWTF. 
On my research I found out that the flow of program pauses at line 293 of `plugin_handler.py`.
`parser = PTP()`
`parser.parse(pathname=pathname)`
where pathname sent to the above function was `owtf_review/targets/https__testasp.vulnweb.com_/partial/Nikto_Unauthenticated/active`

**Comment by DePierre** [comment]
@DarKnight-- I am surprised that ptp freezes owtf :/ Would you have a test case that I could reproduce? Does running nikto always results in owtf freezing?

**Comment by DarKnight--** [comment]
@DePierre Yes In current state of OWTF each time it freezes, I am able to regain that position by closing OWTF (using `ctrt + c`) and by rerun that plugin.
![screenshot from 2016-03-14 00 06 52](https://cloud.githubusercontent.com/assets/6971456/13730570/dee23510-e978-11e5-95d8-5555a945b2f7.png)
![screenshot from 2016-03-14 00 07 42](https://cloud.githubusercontent.com/assets/6971456/13730569/de54a088-e978-11e5-808b-41fb1f0005c5.png)

You can see the output in terminal, last print statement is `in this else`.
I have another print statement after that call to the parser `mid of else`, which dose not get executed. I am able to reproduce it each time, which helped in finding the problematic code.

In current situation I have some plugins in paused state which I think are not creating any problem. On rerun if run any paused or new plugins they run perfectly. There is problem with some tools only I guess. 

Hope this helps in finding the real culprit :)

**Comment by DePierre** [comment]
@DarKnight-- My two cents. I find it weird that ptp hangs, mostly because there is no loop or anything in the project source code. Whether it successfully read the report and parse it, or completely fails and raises an exception.

The only scenario I can think of right now is that ptp tries to open a handle on Nikto's report file but the file hasn't been closed by Nikto or OWTF. Therefore, ptp waits on `open()` but Nikto/OWTF is not closing the file, hence the *freeze* situation.

Would it be possible to tarball the Nikto report? At least I could test locally if ptp successfully parses the report or not. Then it would help us understand if the problem comes from the fact that ptp hangs when parsing the report or if it is that file handle thing.

**Comment by ner0x652** [comment]
I do not understand fully this problem, and do not know how this feature is implemented(because for some time I haven't followed the changes in code). Anyway, maybe I can suggest something useful.

Based on what @DePierre wrote, you can try to insert a timeout before ptp tries to open Nikto's report file or when it hangs, you can also view if that file is still opened. For example, before ptp tries to open the file, use `lsof` to see if that file is still opened, thus you'll know if this assumption on file deadlock holds.

**Comment by DarKnight--** [comment]
@DePierre @ner0x652  I used `lsof` and didn't find any file open related to the plugin logs.
this attached file has output of `lsof | grep owtf`
[logs.txt](https://github.com/owtf/owtf/files/171538/logs.txt)

**Comment by 7a** [comment]
This is still happening, I had workers showing various tools as "running" when the tools had really finished hours (or days) ago, which is really messy. On the CLI I could see the tools had finished, had to Control + C OWTF and open it again to pick up the work :(

**Comment by viyatb** [comment]
https://github.com/owtf/owtf/commit/2b2bd2214e538c5e1ed269fb57b75f91dd200e8c and a19cb7d3da79e9e7bf64c87583b79e37f421ead7  should have fixed this by properly removing an child processes for the worker.
