### ISSUE TITLE
Command Execution possible using '&' character in argument

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#503]
If I run command:-  
./owtf.py http://127.0.0.1/&mkdir killer 
then I am able to make a directory "killer" in owtf folder

I have found two solutions yet but they are client-sided
1. give argument containing & in quotes
     e.g. ./owtf.py "http://127.0.0.1/&mkdir killer"
2. use a \ before &
     e.g.  ./owtf.py http://127.0.0.1/\&mkdir killer

**Comment by DePierre** [comment]
@DoomTaper This looks like genuine shell command. If you are in your console and you type:
```bash
git status& echo 'hello'
```
You will see 'hello' in your console. I think you misinterpreted the behaviour here.

**Comment by DoomTaper** [comment]
what if a url contains '&' in it e.g. http://www.website.com?optionone=one&numbertwo=two

**Comment by DePierre** [comment]
@DoomTaper Then you put it between quotes like:
```bash
echo "http://www.website.com?optionone=one&numbertwo=two"
```

This is not a command injection. If you are writing stuff into your terminal, it will try to execute your commands, that is expected behaviour.

A command injection would be when entering "http://www.website.com?optionone=one&numbertwo=two" into the WebUI Add Target and it would execute a bash command.
In your case, this is simply how your terminal work.

**Comment by DoomTaper** [comment]
@DePierre Thanks! :)
