### ISSUE TITLE
Listing plugins option (-l) not working

### ISSUE THREAD

**Issue by DoomTaper** [owtf/owtf#556]
I tried command `./owtf.py -l net` and it shows error:
`sqlalchemy.exc.InvalidRequestError: Entity '<class 'framework.db.models.TestGroup'>' has no property 'type'`

**Comment by delta24** [comment]
Merged in 4e45d761a911a7ebbdedf9648ddd66436113613d.

**Comment by DePierre** [comment]
@delta24 at least test the PR. The fix is wrong.

@DoomTaper By commenting the line that raised an error, you are preventing filtering on plugin types. With your fix, instead of having 120 +/- 5 plugins, ``owtf.py -l web`` shows 600 +/- 30. Do you understand where that 500 hundreds extra plugins come from? Duplicates. Duplicates that were filtered out by the line you commented.

**Comment by DePierre** [comment]
@DoomTaper is working on a proper fix.

**Comment by DePierre** [comment]
@DoomTaper Thank you very much for that fix ;)

**Comment by DoomTaper** [comment]
@DePierre credit goes to you as well :)
