### ISSUE TITLE
Feature Req: OWTF to run scans only on ZEST recordings

### ISSUE THREAD

**Issue by BSec** [owtf/owtf#735]
In a multi module web application or a very big web application, there can be changes as time progress.
You can assume it as a continues development. So in this kind of scenarios, teams are only interested to run security scans/checks only on those webpages or modules or series of steps (ZEST recordings) which are developed or modified recently.

Having this feature will make OWTF more useful on a daily basis and more acceptable for Dev community.
Particularly, more useful for Agile based development environment.

**Comment by DePierre** [comment]
@BSec My 2-cents but what you are requesting is not part of OWTF's objectives.

OWTF provides multiple plugins that help people following well-known security guides (e.g. the OWASP one) when testing applications. The plugins should be seen as `wrappers` around other tools (such as w3af, skipfish, Google custom search) and since they do not provide the feature to test only a subset of pages, OWTF can't provide it either.

What you are requesting can be achieved using Burp or ZAP and they are good for that. OWTF isn't meant to do so.

@7a @delta24 I would suggest to close the issue as `won't-fix`. Would do you think?

**Comment by delta24** [comment]
@DePierre I agree.

**Comment by DePierre** [comment]
@BSec Feel free to reopen the issue if you disagree with our decision.

**Comment by BSec** [comment]
I would still say this kind of option would make the tool more desired by community.
