### ISSUE TITLE
Broken DB password authentication after installing

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#767]
When OWTF is run for the first time the DB authentication fails.
While this can be solved running the DB setup script, this is not very user-friendly and should be avoided.

Steps:

1) Fully up-to-date kali linux
2) Clone UI Improvements Branch:
	git clone -b ui_improvements https://github.com/owtf/owtf.git

3) Run installer
	cd owtf/install/ 
	python install.py
	(say yes to everything)
	
4) Run owtf	

cd /path/to/pentest/directory
/root/owtf/owtf.py 

```
 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
    
ERROR:root:Aborted by Framework: [DB] (psycopg2.OperationalError) FATAL:  password authentication failed for user "owtf_db_user"
FATAL:  password authentication failed for user "owtf_db_user"

Run scripts/db_run.sh to start/setup db
```

**Comment by 7a** [comment]
Seems fixed after the following, but note the sed errors on the DB script, this should also be fixed:

```
bash /root/owtf/scripts/db_run.sh
[+] Postgres running on 127.0.0.1
127.0.0.1:5432
5433
[+] OWTF db config points towards 127.0.0.1:5432
[+] Do you want us to save the new settings for OWTF? [Y/n]
Y
sed: -e expression #1, char 34: unterminated `s' command
sed: -e expression #1, char 26: unterminated `s' command
[+] New database configuration saved
[+] The problem seems to be the user role and db mentioned in /root/.owtf/db.cfg. Do you want us to create them? [Y/n]
Y

------------------------- OWTF Database Helper Script -------------------------
                    Helps in creation of user and database                     
-------------------------------------------------------------------------------

[+] Ensure that you have required values in /root/.owtf/db.cfg

Press Enter to continue

CREATE ROLE
CREATE DATABASE
Having SSL=true in postgres config causes many errors (psycopg2 problem)
Remove SSL=true from the PostgreSQL config?[Y/n]Y
Restarting the postgresql service
```

**Comment by DarKnight24** [comment]
@7a @delta24 I have looked through the bug.

* The broken database link is due to the problem in locating .owtf directory. The problem is when install script runs it creates the `.owtf` directory in current user's home. But when setup_db script is called, it required root privileges and hence it look the `.owtf` folder in root's home. So it is quits with error and database is not created.

* The sed issues occurs when multiple instances of postgresql are  running. On my system postgres is running on 5432 ans 5433 port. Same happens with @7a, have a look at upper comment (line 3 & 4). 

Please suggest the way to tackle the bug.

**Comment by DarKnight24** [comment]
@delta24 @7a I have fixed I issue.
What should I do for II issue?

**Comment by delta24** [comment]
Good! re: the second issue - even though 2 instances are running, where is the config file for the second one?

**Comment by DarKnight24** [comment]
@delta24 There are two postrgesql are running. So when we are grabbing [through](https://github.com/owtf/owtf/blob/develop/scripts/db_run.sh#L32) `$(sudo netstat -lptn | grep "^tcp " | grep postgres | sed 's/\s\+/ /g' | cut -d ' ' -f4 | cut -d ':' -f1)` the returned value is:
```
127.0.0.1
127.0.0.1
```

same when port is [extracted](https://github.com/owtf/owtf/blob/develop/scripts/db_run.sh#L37) on my machine it returns:
```
5432
5433
```

the solution can be when ip and port are extracted instead of matching we can search, weather the saved port is open(by pqsql) or not.

**Comment by delta24** [comment]
@DarKnight24 pick the Postgresql instance running on port specified by the `db.cfg` file in .owtf directory. I think it is 5432 port by default.

**Comment by DarKnight24** [comment]
@delta24 [This variable](https://github.com/owtf/owtf/blob/develop/scripts/db_run.sh#L80) is always 1 irrespective of postgresql service is active or not.

**Comment by melvinvarkey** [comment]
Hey i know this question is not valid here.... but still any of the post was able to solve my problem here, 
Please anyone suggest me a solution for this

**Comment by viyatb** [comment]
@melvinvarkey Try what the error message says. You need to start the PostgreSQL service and setup the OWTF user correctly.
`sh scripts/db_run.sh`
`sh scripts/db_setup.sh init`

**Comment by melvinvarkey** [comment]
@viyatb

**Comment by viyatb** [comment]
@melvinvarkey Please use the latest Kali version - it is Kali Rolling 2016.2.

**Comment by lianfeng30** [comment]
python2 -m owtf

 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org

[-] Loading config from: /Users/x/.owtf/conf/framework.cfg..
ERROR:root:Aborted by Framework: [DB] (psycopg2.OperationalError) FATAL:  role "owtf_db_user" does not exist

Run 'make db-run' to start/setup db
