### ISSUE TITLE
[UI Improvements] Unable to use UI since it is "waiting for socket"

### ISSUE THREAD

**Issue by 7a** [owtf/owtf#771]
When trying to use the new UI to review and rank plugins for a given target, I am unable to do so since, the target panel (http://127.0.0.1:8009/ui/targets/6) is polling constantly and hence hogs the available sockets on 127.0.0.1, making the UI completely unusable.

The whole point of the OWTF UI is that it should be as fast as possible to review and rank everything. For this reason, I very seriously doubt that endpoints such as http://127.0.0.1:8009/ui/targets/6 should poll anything, especially when we know this is going to poll heavy endpoints that will make the UI unresponsive.

In general: We need to keep polling to a minimum, and simply do not poll any heavy endpoint, when possible. The UI responsiveness is of *much* more important than any data retrieved via polling.

Edit: In this particular case, this happened as i tried to open the "active" plugin files for the ssl plugin, but this will happen whenever you try to open any files.

Chrome CPU: 60%
OWTF CPU: 0%

Edit 2: We need to review that ALL plugins open files via the http://127.0.0.1:8010/ backend, this will minimise issues like this. Right now, opening ssl active files uses http://127.0.0.1:8009/ (same backend as the UI), therefore Chrome hangs "waiting for socket" (because background polling used up the sockets).

Suggestion:
 - All plugins to use http://127.0.0.1:8010/ for serving files (so this does not burn any active connection socket)
 - All UI polling to be done using a NEW listener, maybe http://127.0.0.1:8011/, to avoid hogging sockets for the main UI, so when the user clicks something, this sill goes through http://127.0.0.1:8009/ and works
 - Other endpoints, such as ranking, could also have their own listener, i.e. :8012 to further reduce the chance of a frozen UI <-- This bug also prevents the user from ranking plugins in the already loaded report, since it currently uses the same hogged host:port combination and Chrome remains "waiting for socket"
 - After implementing the abvove, all UI polling should be as infrequent and lightweight as possible

**Comment by saganshul** [comment]
@7a 
Thank you for reviewing the new UI.
* First I think there is no polling on report page. Initially, UI sends a lot of requests to server to load the data for plugins. As you can see here:

![screenshot from 2016-11-08 14-15-13](https://cloud.githubusercontent.com/assets/11960067/20092369/d16c1aac-a5bd-11e6-9b88-9b5e8524faf6.png)
 That's why you are facing this hoging issue of UI. After completing all the requests. UI doesn't send any requests to server. Unless you have asked for some filtering.
* I send these lot of requests because last time we have decided to break the request in multiple parts and you suggested this method to load names first and then for each plugin load data. Now this cannot be done on opening of accordion because we want plugin_type buttons, rank of plugin on plugin itself.
![ccc7526808286068c43e7815d746d59b](https://cloud.githubusercontent.com/assets/11960067/20092473/66a3f0c2-a5be-11e6-9068-16d5b4a88555.png)
* Solution for this is what I am thinking is we will not send data requests for all the plugins we can send requests for plugins which are visible on screen and as user scrolls we can load data for other plugins accordingly.


* Second:I think we are already serving files on 8010. When you click on browse button, it will open a new tab at localhost:8010. Can you put screenshot or something, so that I can understand what are you talking about?

**Comment by DarKnight24** [comment]
@saganshul Is it fixed?

**Comment by saganshul** [comment]
@DarKnight24 listener is not created yet but UI optimisation is done :) PR is not reviewed yet.

**Comment by delta24** [comment]
@saganshul can you go ahead with the listener?

**Comment by saganshul** [comment]
@delta24 , I think it is actually not needed now because we are making only 1 ajax request in initial loading of report.

**Comment by delta24** [comment]
Merged in ui_improvements branch.
