### ISSUE TITLE
pip 2 could not be installed in ubuntu.

### ISSUE THREAD

**Issue by jack17529** [owtf/owtf#814]
When during installation this command is used-
pip2 install --upgrade -r /home/jack/owtf/install/owtf.pip

gives error-
IOError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/dist-packages/test_cookies.pyc'

I searched inside /usr/local/lib/python2.7/dist-packages.
could not find test_cookies.pyc

I have no idea for the importance of test_cookies.pyc .

I am working on ubuntu 16.04

**Comment by DePierre** [comment]
@jack17529 Hey there. The error message seems to be due to permission error (`Permission denied`) when running pip. Depending on your setup, you might need to run pip2 as root to have write permission in `/usr/local/lib/`.

Try running `sudo pip2 install --upgrade -r /home/jack/owtf/install/owtf.pip` and see it is successful.

Please re-open the issue if there is another error but the problem you have is not related to owtf.

**Comment by jack17529** [comment]
@DePierre  how did you figured out that problem was in the pip2 install --upgrade -r /home/jack/owtf/install/owtf.pip

and not /usr/local/lib/python2.7/dist-packages/test_cookies.pyc

**Comment by DePierre** [comment]
@jack17529 by reading the error message :)

`Permission denied` means what it means. And based on your installation path (`/usr/local/lib/`), it was likely that pip was run with a low privileged user while the target installation path required root privilege to write to.

Did you solve the issue by the way?
