### ISSUE TITLE
Aborted by framework: Files required for SSL MiTM are missing. Please run the install script

### ISSUE THREAD

**Issue by guyenko** [owtf/owtf#998]
While running owtf, the process stops with the error: 

Aborted by Framework: Files required for SSL MiTM are missing. Please run the install script. 

## Expected Behavior

The process starts without error.
## Current Behavior

It fails
## Possible Solution

Based on historical data. This issue is due to not having a certificate. I followed the instructions provided 

openssl genrsa -des3 -our ~/.owtf/proxy/ca.key 
openssl req -new -x509 -days 3650 -key !/.owtf/proxy/ca.key -out ~/.owtf/proxy/ca.ctr 

These steps complete without errors. However, the error remains. . 

## Steps to Reproduce (for bugs)

1.
2.
3.
4.

## Your Environment

* Installation method used:
Manual 
created database user and database in postgresql
cloned git repository
ran python install.py 
* Version/branch used:
* Operating System and version (like Kali, Debian, ArchLinux, etc):
Kali Rolling 

* pip/setuptools version:
pip version 18
* sudo access:
Yes

**Comment by viyatb** [comment]
What OWTF branch are you using?

**Comment by mzfr** [comment]
@viyatb I am having the same problem. I am trying to setup a develop environment.
I am using the `develop` branch. I ran the installation script and when I did `python -m owtf` I am getting:
```
         _____ _ _ _ _____ _____
        |     | | | |_   _|   __|
        |  |  | | | | | | |   __|
        |_____|_____| |_| |__|

            @owtfp
        http://owtf.org
        Version: 2.4.0

[+] Loading /home/mzfr/dev/owtf/owtf/data/conf/framework.yaml..
[+] Loading /home/mzfr/dev/owtf/owtf/data/conf/general.yaml..
[+] Loading resources from: /home/mzfr/.owtf/conf/resources.cfg..
[+] Loading framework please wait..
[!] Starting HTTP(s) proxy server at 127.0.0.1:8008
[-] Aborted by Framework: Files required for SSL MiTM are missing.Please run the install script
```

**Comment by viyatb** [comment]
@mzfr if you are on develop branch, you should be able to do `python setup.py install; owtf`. Let me know if that works.

**Comment by mzfr** [comment]
@viyatb I tried the method you suggested and I am still having the same issue.

**Comment by guyenko** [comment]
Has this been addressed?

**Comment by viyatb** [comment]
This should be fixed in the latest develop. Can you try again?

**Comment by viyatb** [comment]
@guyenko let me know if this issue still persists on a clean installation of OWTF on Kali 2018.

**Comment by mmaruf212** [comment]
Getting the same issue for OWTF version 2.6 in Kali linux running in AWS EC2 instance

[+] Loading /usr/local/lib/python2.7/dist-packages/owtf-2.6.0-py2.7.egg/owtf/data/conf/framework.yaml..
[+] Loading /usr/local/lib/python2.7/dist-packages/owtf-2.6.0-py2.7.egg/owtf/data/conf/general.yaml..
[+] Loading resources from: /home/ec2-user/.owtf/conf/resources.cfg..
[+] Loading framework please wait..
[!] Starting HTTP(s) proxy server at 127.0.0.1:8008
[-] Aborted by Framework: Files required for SSL MiTM are missing.Please run the install script

**Comment by scotmatson** [comment]
Just encountered this issue in latest Kali release, 2020.4

Couldn't run the `python setup.py develop` command without first installing missing dependencies `curl-config` and `psychopg2` and now receiving this error when running owtf.

Recommended Docker installation hangs on execution leaving both paths to installation effectively broken.

**Comment by spmishra121** [comment]
Hi @viyatb

I am getting the same error after following all installation steps. I am not using docker. I am doing manual installation.

**Kali- LInux Version: 2022.3**


┌──(kali㉿kali)-[~/owtf]
└─$ sudo **python3.7** setup.py develop                                                
running develop
running egg_info
writing owtf.egg-info/PKG-INFO
writing dependency_links to owtf.egg-info/dependency_links.txt
writing entry points to owtf.egg-info/entry_points.txt
writing requirements to owtf.egg-info/requires.txt
writing top-level names to owtf.egg-info/top_level.txt
reading manifest file 'owtf.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*' under directory 'owtf/webui'
warning: no previously-included files found matching ''node_modules''
warning: no previously-included files found matching ''node_modules.*''
writing manifest file 'owtf.egg-info/SOURCES.txt'
running build_ext
Creating /usr/local/lib/python3.7/site-packages/owtf.egg-link (link to .)
Removing owtf 2.6.0 from easy-install.pth file
Adding owtf 2.6.0 to easy-install.pth file
Installing owtf script to /usr/local/bin
Installing owtf script to /usr/local/bin

Installed /home/kali/owtf
Processing dependencies for owtf==2.6.0
Searching for sphinxcontrib-httpdomain==1.7.0
Best match: sphinxcontrib-httpdomain 1.7.0
Processing sphinxcontrib_httpdomain-1.7.0-py3.7.egg
sphinxcontrib-httpdomain 1.7.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/sphinxcontrib_httpdomain-1.7.0-py3.7.egg
Searching for sphinx-py3doc-enhanced-theme==2.3.1
Best match: sphinx-py3doc-enhanced-theme 2.3.1
Processing sphinx_py3doc_enhanced_theme-2.3.1-py3.7.egg
sphinx-py3doc-enhanced-theme 2.3.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/sphinx_py3doc_enhanced_theme-2.3.1-py3.7.egg
Searching for Sphinx==1.7.4
Best match: Sphinx 1.7.4
Processing Sphinx-1.7.4-py3.7.egg
Sphinx 1.7.4 is already the active version in easy-install.pth
Installing sphinx-apidoc script to /usr/local/bin
Installing sphinx-autogen script to /usr/local/bin
Installing sphinx-build script to /usr/local/bin
Installing sphinx-quickstart script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/Sphinx-1.7.4-py3.7.egg
Searching for pyotp==2.6.0
Best match: pyotp 2.6.0
Processing pyotp-2.6.0-py3.7.egg
pyotp 2.6.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pyotp-2.6.0-py3.7.egg
Searching for bs4==0.0.1
Best match: bs4 0.0.1
Processing bs4-0.0.1-py3.7.egg
bs4 0.0.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/bs4-0.0.1-py3.7.egg
Searching for PyJWT==1.7.1
Best match: PyJWT 1.7.1
Processing PyJWT-1.7.1-py3.7.egg
PyJWT 1.7.1 is already the active version in easy-install.pth
Installing pyjwt script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/PyJWT-1.7.1-py3.7.egg
Searching for uuid==1.30
Best match: uuid 1.30
Processing uuid-1.30-py3.7.egg
uuid 1.30 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/uuid-1.30-py3.7.egg
Searching for bcrypt==3.2.0
Best match: bcrypt 3.2.0
Processing bcrypt-3.2.0-py3.7-linux-x86_64.egg
bcrypt 3.2.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/bcrypt-3.2.0-py3.7-linux-x86_64.egg
Searching for tornado==5.1.1
Best match: tornado 5.1.1
Processing tornado-5.1.1-py3.7-linux-x86_64.egg
tornado 5.1.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/tornado-5.1.1-py3.7-linux-x86_64.egg
Searching for sqlalchemy-mixins==1.5.3
Best match: sqlalchemy-mixins 1.5.3
Processing sqlalchemy_mixins-1.5.3-py3.7.egg
sqlalchemy-mixins 1.5.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/sqlalchemy_mixins-1.5.3-py3.7.egg
Searching for SQLAlchemy==1.3.0
Best match: SQLAlchemy 1.3.0
Processing SQLAlchemy-1.3.0-py3.7-linux-x86_64.egg
SQLAlchemy 1.3.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/SQLAlchemy-1.3.0-py3.7-linux-x86_64.egg
Searching for six==1.15.0
Best match: six 1.15.0
Processing six-1.15.0-py3.7.egg
six 1.15.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/six-1.15.0-py3.7.egg
Searching for selenium==3.4.3
Best match: selenium 3.4.3
Processing selenium-3.4.3-py3.7.egg
selenium 3.4.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/selenium-3.4.3-py3.7.egg
Searching for requests==2.22.0
Best match: requests 2.22.0
Processing requests-2.22.0-py3.7.egg
requests 2.22.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/requests-2.22.0-py3.7.egg
Searching for PyYAML==5.4.1
Best match: PyYAML 5.4.1
Processing PyYAML-5.4.1-py3.7-linux-x86_64.egg
PyYAML 5.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/PyYAML-5.4.1-py3.7-linux-x86_64.egg
Searching for pyOpenSSL==22.1.0
Best match: pyOpenSSL 22.1.0
Processing pyOpenSSL-22.1.0-py3.7.egg
pyOpenSSL 22.1.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pyOpenSSL-22.1.0-py3.7.egg
Searching for pycurl==7.43.0.2
Best match: pycurl 7.43.0.2
Processing pycurl-7.43.0.2-py3.7-linux-x86_64.egg
pycurl 7.43.0.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pycurl-7.43.0.2-py3.7-linux-x86_64.egg
Searching for owtf-ptp==0.4.3
Best match: owtf-ptp 0.4.3
Processing owtf_ptp-0.4.3-py3.7.egg
owtf-ptp 0.4.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/owtf_ptp-0.4.3-py3.7.egg
Searching for psycopg2-binary==2.8
Best match: psycopg2-binary 2.8
Processing psycopg2_binary-2.8-py3.7-linux-x86_64.egg
psycopg2-binary 2.8 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/psycopg2_binary-2.8-py3.7-linux-x86_64.egg
Searching for psutil==5.7.2
Best match: psutil 5.7.2
Processing psutil-5.7.2-py3.7-linux-x86_64.egg
psutil 5.7.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/psutil-5.7.2-py3.7-linux-x86_64.egg
Searching for pexpect==4.6.0
Best match: pexpect 4.6.0
Processing pexpect-4.6.0-py3.7.egg
pexpect 4.6.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pexpect-4.6.0-py3.7.egg
Searching for Markdown==2.6.9
Best match: Markdown 2.6.9
Processing Markdown-2.6.9-py3.7.egg
Markdown 2.6.9 is already the active version in easy-install.pth
Installing markdown_py script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/Markdown-2.6.9-py3.7.egg
Searching for ipaddr==2.2.0
Best match: ipaddr 2.2.0
Processing ipaddr-2.2.0-py3.7.egg
ipaddr 2.2.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/ipaddr-2.2.0-py3.7.egg
Searching for hrt==0.1.0
Best match: hrt 0.1.0
Processing hrt-0.1.0-py3.7.egg
hrt 0.1.0 is already the active version in easy-install.pth
Installing hrt script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/hrt-0.1.0-py3.7.egg
Searching for future==0.16.0
Best match: future 0.16.0
Processing future-0.16.0-py3.7.egg
future 0.16.0 is already the active version in easy-install.pth
Installing futurize script to /usr/local/bin
Installing pasteurize script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/future-0.16.0-py3.7.egg
Searching for dnspython==1.15.0
Best match: dnspython 1.15.0
Processing dnspython-1.15.0-py3.7.egg
dnspython 1.15.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/dnspython-1.15.0-py3.7.egg
Searching for cookies==2.2.1
Best match: cookies 2.2.1
Processing cookies-2.2.1-py3.7.egg
cookies 2.2.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/cookies-2.2.1-py3.7.egg
Searching for cffi==1.14.1
Best match: cffi 1.14.1
Processing cffi-1.14.1-py3.7-linux-x86_64.egg
cffi 1.14.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/cffi-1.14.1-py3.7-linux-x86_64.egg
Searching for blinker==1.6.2
Best match: blinker 1.6.2
Processing blinker-1.6.2-py3.7.egg
blinker 1.6.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/blinker-1.6.2-py3.7.egg
Searching for sphinxcontrib-websupport==1.2.4
Best match: sphinxcontrib-websupport 1.2.4
Processing sphinxcontrib_websupport-1.2.4-py3.7.egg
sphinxcontrib-websupport 1.2.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/sphinxcontrib_websupport-1.2.4-py3.7.egg
Searching for snowballstemmer==2.2.0
Best match: snowballstemmer 2.2.0
Processing snowballstemmer-2.2.0-py3.7.egg
snowballstemmer 2.2.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/snowballstemmer-2.2.0-py3.7.egg
Searching for setuptools==47.1.0
Best match: setuptools 47.1.0
Adding setuptools 47.1.0 to easy-install.pth file
Installing easy_install script to /usr/local/bin
Installing easy_install-3.8 script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages
Searching for packaging==23.1
Best match: packaging 23.1
Processing packaging-23.1-py3.7.egg
packaging 23.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/packaging-23.1-py3.7.egg
Searching for imagesize==1.4.1
Best match: imagesize 1.4.1
Processing imagesize-1.4.1-py3.7.egg
imagesize 1.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/imagesize-1.4.1-py3.7.egg
Searching for docutils==0.19
Best match: docutils 0.19
Processing docutils-0.19-py3.7.egg
docutils 0.19 is already the active version in easy-install.pth
Installing rst2xml.py script to /usr/local/bin
Installing rst2pseudoxml.py script to /usr/local/bin
Installing rst2html4.py script to /usr/local/bin
Installing rst2html5.py script to /usr/local/bin
Installing rst2s5.py script to /usr/local/bin
Installing rst2odt.py script to /usr/local/bin
Installing rst2odt_prepstyles.py script to /usr/local/bin
Installing rst2latex.py script to /usr/local/bin
Installing rst2man.py script to /usr/local/bin
Installing rstpep2html.py script to /usr/local/bin
Installing rst2xetex.py script to /usr/local/bin
Installing rst2html.py script to /usr/local/bin
Installing docutils script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/docutils-0.19-py3.7.egg
Searching for Babel==2.12.1
Best match: Babel 2.12.1
Processing Babel-2.12.1-py3.7.egg
Babel 2.12.1 is already the active version in easy-install.pth
Installing pybabel script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/Babel-2.12.1-py3.7.egg
Searching for alabaster==0.7.13
Best match: alabaster 0.7.13
Processing alabaster-0.7.13-py3.7.egg
alabaster 0.7.13 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/alabaster-0.7.13-py3.7.egg
Searching for Pygments==2.15.1
Best match: Pygments 2.15.1
Processing Pygments-2.15.1-py3.7.egg
Pygments 2.15.1 is already the active version in easy-install.pth
Installing pygmentize script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/Pygments-2.15.1-py3.7.egg
Searching for Jinja2==3.1.2
Best match: Jinja2 3.1.2
Processing Jinja2-3.1.2-py3.7.egg
Jinja2 3.1.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/Jinja2-3.1.2-py3.7.egg
Searching for beautifulsoup4==4.12.2
Best match: beautifulsoup4 4.12.2
Processing beautifulsoup4-4.12.2-py3.7.egg
beautifulsoup4 4.12.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/beautifulsoup4-4.12.2-py3.7.egg
Searching for urllib3==1.25.11
Best match: urllib3 1.25.11
Processing urllib3-1.25.11-py3.7.egg
urllib3 1.25.11 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/urllib3-1.25.11-py3.7.egg
Searching for idna==2.8
Best match: idna 2.8
Processing idna-2.8-py3.7.egg
idna 2.8 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/idna-2.8-py3.7.egg
Searching for chardet==3.0.4
Best match: chardet 3.0.4
Processing chardet-3.0.4-py3.7.egg
chardet 3.0.4 is already the active version in easy-install.pth
Installing chardetect script to /usr/local/bin

Using /usr/local/lib/python3.7/site-packages/chardet-3.0.4-py3.7.egg
Searching for certifi==2022.12.7
Best match: certifi 2022.12.7
Processing certifi-2022.12.7-py3.7.egg
certifi 2022.12.7 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/certifi-2022.12.7-py3.7.egg
Searching for cryptography==38.0.4
Best match: cryptography 38.0.4
Processing cryptography-38.0.4-py3.7-linux-x86_64.egg
cryptography 38.0.4 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/cryptography-38.0.4-py3.7-linux-x86_64.egg
Searching for lxml==4.9.2
Best match: lxml 4.9.2
Processing lxml-4.9.2-py3.7-linux-x86_64.egg
lxml 4.9.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/lxml-4.9.2-py3.7-linux-x86_64.egg
Searching for Js2Py==0.74
Best match: Js2Py 0.74
Processing Js2Py-0.74-py3.7.egg
Js2Py 0.74 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/Js2Py-0.74-py3.7.egg
Searching for ptyprocess==0.7.0
Best match: ptyprocess 0.7.0
Processing ptyprocess-0.7.0-py3.7.egg
ptyprocess 0.7.0 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/ptyprocess-0.7.0-py3.7.egg
Searching for pycparser==2.21
Best match: pycparser 2.21
Processing pycparser-2.21-py3.7.egg
pycparser 2.21 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pycparser-2.21-py3.7.egg
Searching for sphinxcontrib-serializinghtml==1.1.5
Best match: sphinxcontrib-serializinghtml 1.1.5
Processing sphinxcontrib_serializinghtml-1.1.5-py3.7.egg
sphinxcontrib-serializinghtml 1.1.5 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/sphinxcontrib_serializinghtml-1.1.5-py3.7.egg
Searching for pytz==2023.3
Best match: pytz 2023.3
Processing pytz-2023.3-py3.7.egg
pytz 2023.3 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pytz-2023.3-py3.7.egg
Searching for MarkupSafe==2.1.2
Best match: MarkupSafe 2.1.2
Processing MarkupSafe-2.1.2-py3.7-linux-x86_64.egg
MarkupSafe 2.1.2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/MarkupSafe-2.1.2-py3.7-linux-x86_64.egg
Searching for soupsieve==2.4.1
Best match: soupsieve 2.4.1
Processing soupsieve-2.4.1-py3.7.egg
soupsieve 2.4.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/soupsieve-2.4.1-py3.7.egg
Searching for tzlocal==5.0b2
Best match: tzlocal 5.0b2
Processing tzlocal-5.0b2-py3.7.egg
tzlocal 5.0b2 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/tzlocal-5.0b2-py3.7.egg
Searching for pyjsparser==2.7.1
Best match: pyjsparser 2.7.1
Processing pyjsparser-2.7.1-py3.7.egg
pyjsparser 2.7.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/pyjsparser-2.7.1-py3.7.egg
Searching for backports.zoneinfo==0.2.1
Best match: backports.zoneinfo 0.2.1
Processing backports.zoneinfo-0.2.1-py3.7-linux-x86_64.egg
backports.zoneinfo 0.2.1 is already the active version in easy-install.pth

Using /usr/local/lib/python3.7/site-packages/backports.zoneinfo-0.2.1-py3.7-linux-x86_64.egg
Finished processing dependencies for owtf==2.6.0
Running post install
/home/kali/owtf/scripts/install.sh: line 12: /home/kali/owtf/scripts/platform_config.sh: No such file or directory
 _____ _ _ _ _____ _____
|     | | | |_   _|   __|
|  |  | | | | | | |   __|
|_____|_____| |_| |__|

        @owtfp
    http://owtf.org
[*] Thanks for installing OWTF! 
[!] There will be lot of output, please be patient :)
[*] Installing pre-commit and black for git hooks...
/home/kali/owtf/scripts/install.sh: line 199: /usr/local/bin/pip: cannot execute: required file not found
/home/kali/owtf/scripts/install.sh: line 200: /usr/local/bin/pip: cannot execute: required file not found
/home/kali/owtf/scripts/install.sh: line 201: /usr/local/bin/pre-commit: cannot execute: required file not found
[!] Skipping copying directory conf 
[!] Skipping copying directory dictionaries 
[!] Skipping copying directory tools 
[*] '/root/.owtf/proxy/certs/ca.crt' already exists. Nothing done.
[*] Installing NPM...
v15.0.1 is already installed.
Now using node v15.0.1 (npm v7.0.3)
default -> node (-> v15.0.1)
[*] npm successfully installed.

changed 1 package, and audited 1 package in 1s

found 0 vulnerabilities
[*] Installing node dependencies.
warning package.json: "dependencies" has dependency "@types/react" with range "17.0.14" that collides with a dependency in "devDependencies" of the same name with version "^18.0.28"
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
warning owtf@1.0.0: "dependencies" has dependency "@types/react" with range "17.0.14" that collides with a dependency in "devDependencies" of the same name with version "^18.0.28"
warning Resolution field "@types/react@17.0.14" is incompatible with requested version "@types/react@^16.9.5"
error expect@28.1.3: The engine "node" is incompatible with this module. Expected version "^12.13.0 || ^14.15.0 || ^16.10.0 || >=17.0.0". Got "15.0.1"
error Found incompatible module.
[*] Yarn dependencies successfully installed.
[*] Building using webpack.
[*] Build successful
--> Installing dictionaries and tools
python scripts/install_tools.py
/bin/bash: line 1: python: command not found
make: *** [Makefile:78: post-install] Error 127
[*] Finished!
[*] Start OWTF by running cd path/to/pentest/directory; owtf
[!] Please add a new JWT_SECRET_KEY in the settings file located in owtf/owtf/settings.py 
[!] Please setup SMTP server of your choice in the settings file located in owtf/owtf/settings.py 
                                                                                                                                                                                                                                           
┌──(kali㉿kali)-[~/owtf]
└─$ owtf

         _____ _ _ _ _____ _____                                                                                                                                                                                                           
        |     | | | |_   _|   __|                                                                                                                                                                                                          
        |  |  | | | | | | |   __|                                                                                                                                                                                                          
        |_____|_____| |_| |__|                                                                                                                                                                                                             
                                                                                                                                                                                                                                           
            @owtfp                                                                                                                                                                                                                         
        http://owtf.org                                                                                                                                                                                                                    
        Version: 2.6.0                                                                                                                                                                                                                     
                                                                                                                                                                                                                                           
[+] Loading /home/kali/owtf/owtf/data/conf/framework.yaml..
/home/kali/owtf/owtf/managers/config.py:35: YAMLLoadWarning: calling yaml.load() without Loader=... is deprecated, as the default Loader is unsafe. Please read https://msg.pyyaml.org/load for full details.
  config_map = yaml.load(FileOperations.open(file_path, "r"))
[+] Loading /home/kali/owtf/owtf/data/conf/general.yaml..
[+] Loading resources from: /home/kali/.owtf/conf/resources.cfg..
[+] Loading framework please wait..
[!] Starting HTTP(s) proxy server at 127.0.0.1:8008
[-] Aborted by Framework: Files required for SSL MiTM are missing.Please run the install script
